config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :users, only: [:show, :destroy]
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
  resources :items do
    collection do
      get "get_delivery_method"
      get "set_parents"
      get "set_children"
      get "set_grandchildren"
    end
    member do
      get "buy"
      get "pay"
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand, dependent: :destroy, optional: true
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :brand



  enum status: { sell: 0, buy: 1 , trading:2}
  scope :on_sell, -> { where(status: 0) }

  enum shipping_cost: { 送料込み（出品者負担）:0,着払い（購入者負担）:1 }
  enum delivery_area: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum delivery_date:{ "1~2日で発送": 0, "2~3日で発送": 1, "4~7日で発送": 2 }
  enum size:{ "FREE SIZE": 0, "XXS以下": 1, "XS(SS)": 2, "S": 3, "M": 4, "L": 5, "XL(LL)": 6, "2XL(3L)": 7, "3XL(4L)": 8, "4XL(5L)以上": 9 }
  enum condition:{ 新品、未使用: 0, 未使用に近い: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5 }
  enum delivery_method: { "未定": 0, "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3, "普通郵便（定型、定型外）": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8 }

  validate :img_erorr
  validates :name, :text, :category_id, :size, :condition, :shipping_cost, :delivery_method, :delivery_area, :delivery_date,  :price, :seller_id, presence: true
  validates :text, length: { maximum: 1000 }
  validates :price, numericality: { greater_than: 299, less_than: 10000000 }

  def img_erorr
    if images.present?
    else
      errors.add(:url, "は1枚以上登録してください")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_item, only: [:show, :edit, :update, :buy, :destroy,:pay]
  before_action :set_parent, only: [:new, :create,:edit, :update, :destroy, :set_parents]
  before_action :item_show_buy,   only:[:pay, :buy]

  def index
    @items = Item.on_sell.includes([:images]).order(created_at: :desc)
  end


  def show
    @user = User.find_by(id: @item.seller_id)
    @category = Category.find_by(id: @item.category_id)
    @brand = Brand.find_by(id: @item.brand_id)
  end


  def new
    @item = Item.new
    @item.images.build
    @item.build_brand
  end

  def get_delivery_method
  end

  def set_parents
  end

  def set_children
    @children = Category.where(ancestry: params[:parent_id])
  end

  def set_grandchildren
    @grandchildren = Category.where(ancestry: params[:ancestry])
  end

  def edit
    @children = @parents
    @grandchildren = Category.where(ancestry: params[:ancestry])
    @category_child_array = @item.category.parent.parent.children
    @category_grandchild_array = @item.category.parent.children
  end

  def buy
    @address = Address.find(current_user.id)
    if user_signed_in? && current_user.id == @item.seller_id
    @item = Item.find(params[:id])
    @children = Category.where(ancestry: params[:parent_id])
    @grandchildren = Category.where(ancestry: params[:ancestry])
    else
    redirect_to root_path
    end

  end

  def create
    @item = Item.new(item_params)
    if @item.save
    else
      @item.images.build
      render :new
    end
  end

  def update
    imageLength = @item.images.length
    deleteImage = 0

    for num in 0..9
      if params[:item][:images_attributes][num.to_s] != nil
        if params[:item][:images_attributes][num.to_s][:_destroy] == "1"
          deleteImage += 1
        end
      end
    end
    if @item.valid? && !@item.images.empty? && imageLength != deleteImage
      @item.update(item_params) if user_signed_in? && current_user.id == @item.seller_id
      redirect_to item_path
    else
      redirect_to edit_item_path(@item)
    end
  end

  def destroy
    @item.destroy if user_signed_in? && current_user.id == @item.seller_id
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    if user_signed_in? && current_user.id == @item.seller_id
      redirect_to root_path
    else
      @address = Address.find(current_user.id)
      unless @item.buy?
        @card = CreditCard.find_by(user_id: current_user.id)
        if @card.present?
          Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
          customer = Payjp::Customer.retrieve(@card.customer_id)
          @customer_card = customer.cards.retrieve(@card.card_id)

          @card_brand = @customer_card.brand
          case @card_brand
          when "Visa"
            @card_src = "visa.png"
          when "JCB"
            @card_src = "jcb.png"
          when "Psypal"
            @card_src = "paypal.png"
          when "MasterCard"
            @card_src = "master.png"
          when "American Express"
            @card_src = "amex.png"
          when "Diners Club"
            @card_src = "diners.png"
          when "Discover"
            @card_src = "discover.png"
          end

          @exp_month = @customer_card.exp_month.to_s
          @exp_year = @customer_card.exp_year.to_s.slice(2,3)
        end
      else
        redirect_to item_path(@item)
      end
    end
  end

  def pay
    unless @item.buy?
      @card = CreditCard.find_by(user_id: current_user.id)
      if @card.present?
        @item.buyer_id = current_user.id
        @item.status = 1
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
        @charge = Payjp::Charge.create(
        amount: @item.price,
        customer: @card.customer_id,
        currency: 'jpy'
        )
        @item.save!
      else
        redirect_to new_credit_card_path, alert: "クレジットカードを登録してください"
      end
    else
      redirect_to item_path(@item), alert: "購入が完了しました"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_parent
      @parents = Category.where(ancestry: nil)
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :text, :status, :size, :condition, :shipping_cost, :delivery_method, :delivery_area, :delivery_date, :category_id, brand_attributes: [:name], images_attributes: [:url, :_destroy, :id]).merge(seller_id: current_user.id, status: 0)
    end

    #購入済の商品、出品者はpay,buyページにurlから飛べないように
    def  item_show_buy
      if @item.buyer_id.present? || current_user.id == @item.seller_id
        redirect_to root_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  
  # 円マーク値段
  def enmark_item_price(item)
    "¥#{item.price}"  
  end

  #  郵便番号にハイフン
  def user_post_code(address)
     address.postal_code.to_s.insert(3, "-")
  end

  # 都道府県から番地をまとめ、ビル名があれば表示
  def user_address_info(address)
    if address.building.blank?
      address.prefecture + address.city + address.block
    else
     str = "#{address.prefecture}#{address.city}#{address.block}\n#{address.building}"
      str.chomp
    end
  end

  #ユーザーのフルネーム
  def user_full_name(address)
    address.send_first_name+address.send_name
  end
  
end

app/views/items/_banner.html.haml
.banner
 .banner__innner
  .banner__innner__title だれでもかんたん、人生を変えるフリマアプリ
  .banner__innner__text 今すぐ無料ダウンロード！
  .banner__innner__icon
   = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", width: '180', alt: "サンプル画像", class:"app"), "https://www.apple.com/jp/ios/app-store/"
   = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", width: '180', alt: "サンプル画像",class:"ggl"), "https://play.google.com/store"

app/views/items/_footer.html.haml
.top-footer
 %ul.top-footer__contents
  %li.top-footer__contents__content
   %h2.top-footer__contents__content__head FURIMAについて
   %ul
    %li
     = link_to "会社概要概要(運営会社)", "/"
    %li
     = link_to "プライバシーポリシー", "/"
    %li
     = link_to "FURIMA利用規約", "/"
    %li
     = link_to "ポイントに関する特約", "/"

  %li.top-footer__contents__content
   %h2.top-footer__contents__content__head FURIMAを見る
   %ul
    %li
     = link_to "カテゴリー一覧", "/"
    %li
     = link_to "ブランド一覧", "/"


  %li.top-footer__contents__content
   %h2.top-footer__contents__content__head ヘルプ＆ガイド
   %ul
    %li
     = link_to "FURIMAガイド", "/"
    %li
     = link_to "FURIMAロゴ利用ガイドライン", "/"
    %li
     = link_to "お知らせ", "/"

 .top-footer__logo
  = link_to image_tag("logo-white.png", width: '160', alt: "サンプル画像", class:"top-footer__logo"), "/"
 %p © FURIMA

app/views/items/_header.html.haml
.top-header
 .top-header__inner
  .top-header__inner__main
   .top-header__inner__main__icon
    = link_to image_tag("logo.png", width: '140', alt: "サンプル画像"), "/"
   .top-header__inner__main__serch
   .top-header__inner__main__resultlists
  .top-header__inner__nav
   %ul.top-header__inner__nav__left
    //= link_to "カテゴリー", "/", class: "top-header__inner__nav__left__category"
    //= link_to "ブランド", "/", class: "top-header__inner__nav__left__brand"
   %ul.top-header__inner__nav__right
    - if user_signed_in?
     = link_to "マイページ", user_path(current_user), class:  "top-header__inner__nav__right__my-page"
     = link_to "ログアウト", destroy_user_session_path, method: :delete, class:  "top-header__inner__nav__right__my-page"
    - else
     = link_to "ログイン",  new_user_session_path, class: "top-header__inner__nav__right__login"
     = link_to "新規会員登録", new_user_registration_path, class: "top-header__inner__nav__right__signup"

app/views/items/_main.html.haml
.top-main
 %section.top-main__visual
  .top-main__visual__content
   %h2.top-main__visual__content__subtitile
    %br
    人生を変えるフリマアプリ
   %p.top-main__visual__content__text
    FURIMAはだれでもかんたんに出品・購入できる
    %br
    フリマアプリです
   .top-main__visual__content__btn
    = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", width: '180', alt: "サンプル画像", class:"app"), "https://www.apple.com/jp/ios/app-store/"
    = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", width: '180', alt: "サンプル画像",class:"ggl"), "https://play.google.com/store"

 .top-main__introduction
  %h2.top-main__introduction__subtitle
   FURIMAが選ばれる3つの理由
  %ul.top-main__introduction__lists
   %li.top-main__introduction__lists__list
    .top-main__introduction__lists__list__pict
     %span.number
      1
     = image_tag("pict-reason-01.jpg",width: '260',alt: "サンプル画像")
    %h3.top-main__introduction__lists__list__text
     %span.top-main__introduction__lists__list__text__span
      3分
     ですぐに出品
    %p.top-main__introduction__lists__list__description
     スマホで入力するだけで簡単に出品できる！

   %li.top-main__introduction__lists__list
    .top-main__introduction__lists__list__pict
     %span.number
      2
     = image_tag("pict-reason-02.jpg",width: '260',alt: "サンプル画像")
    %h3.top-main__introduction__lists__list__text
     %span.top-main__introduction__lists__list__text__span
      シンプル
     で使いやすい
    %p.top-main__introduction__lists__list__description
     めんどくさい入力は必要なく、検索も購入もスムーズ！

   %li.top-main__introduction__lists__list
    .top-main__introduction__lists__list__pict
     %span.number
      3
     = image_tag("pict-reason-03.jpg",width: '260',alt: "サンプル画像")
    %h3.top-main__introduction__lists__list__text--c
     %span.top-main__introduction__lists__list__text--c__span
      手数料
     業界最安
    %p.top-main__introduction__lists__list__description
     最大3%でお得に出品&購入！

 .top-main__middle
  .top-main__middle__inner
   %h2.top-main__middle__inner__subtitle
    会員数日本一位
   %p.top-main__middle__inner__text
    FURIMAは、フリマアプリで最も人気。
    %br
    出品・購入回数も業界最多です！
    %br
    ほしかったあの商品に出会えるかもしれません。
   .top-main__middle__inner__btn
    = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", width: '180', alt: "サンプル画像", class:"app"), "https://www.apple.com/jp/ios/app-store/"
    = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", width: '180', alt: "サンプル画像",class:"ggl"), "https://play.google.com/store"
 .top-main__features
  %h2.top-main__features__head
   FURIMAの特徴
  .top-main__features__items
   .top-main__features__items__item
    = image_tag("icon-01.png",alt: "サンプル画像",class:"top-main__features__items__item__img")
    %h3.top-main__features__items__item__subtitle
     簡単に売り買いできる
    %p.top-main__features__items__item__detail
     スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
   .top-main__features__items__item
    = image_tag("icon-03.png",alt: "サンプル画像",class:"top-main__features__items__item__img")
    %h3.top-main__features__items__item__subtitle
     売上金は即日振込みに対応
    %p.top-main__features__items__item__detail
     午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
   .top-main__features__items__item
    = image_tag("icon-04.png",alt: "サンプル画像",class:"top-main__features__items__item__img")
    %h3.top-main__features__items__item__subtitle
     様々な支払いに対応
    %p.top-main__features__items__item__detail
     お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。





 .top-main__product__list
  %h2.top-main__product__list__title
   出品された商品一覧
  .top-main__product__list__box
   - @items.each do |item|
    = link_to item_path(id: item.id) ,class:"top-main__product__list__box__item" do
     - item.images.first(1).each do |image|
      = image_tag image.url.to_s,class:"top-main__product__list__box__item__img"
     .top-main__product__list__box__item__body
      %h3.top-main__product__list__box__item__body__name
       = item.name
      .top-main__product__list__box__item__body__details
       %ul
        %li
         = item.price
         = "円"
       %p (税込)

app/views/items/_purchase.html.haml
= link_to new_item_path  do
 .purchase
  .purchase__text 出品する
  .purchase__icon
   = image_tag("icon_camera.png",width:'54')

app/views/items/buy.html.haml
.wrapper
  = render 'partial/new-header'

  .main
    .main__content
      %h.main__content__title
        購入内容の確認
      %section.main__content__item
        .main__content__item__inner
          .main__content__item__inner__box
            %h.main__content__item__inner__box__img
              - @item.images.first(1).each do |image|
                = image_tag image.url.to_s,  size:'130x130'
            .main__content__item__inner__box__detail
              %p.main__content__item__inner__box__detail__item-name
                = @item.name
              %p.main__content__item__inner__box__detail__bold
                = enmark_item_price(@item)
              %span （税込）送料込み
      %section.main__content__buy
        .main__content__buy__inner
          .main__content__buy__inner__price
            .main__content__buy__inner__price__text
              支払い金額
            .main__content__buy__inner__price__int
              = enmark_item_price(@item)
          %section.main__content__buy__inner__section
            .main__content__buy__inner__section__div
              %h 支払い方法
              - if current_user.credit_card.present?
                .main-content__buy__inner__section__div__title
                  .main-content__buy__inner__section__div__title__credit-cards
                    クレジットカード
                  %ul.main-content__buy__inner__section__div__title__credit-cards__contents
                    %li.main-content__buy__inner__section__div__title__credit-cards__contents__list
                    .main-content__buy__inner__section__div__title__credit-cards__contents__list__pay-num
                      = "**** **** **** " + @customer_card.last4
                    .main-content__buy__inner__section__div__title__credit-cards__contents__list__time
                      = @exp_month + " / " + @exp_year
                    .main-content__buy__inner__section__div__title__credit-cards__contents__list__icon
                      = image_tag "#{@card_src}", size: "70x50", class: "credit_card_info__brand__img", alt: @card_brand
                
              - else                
                = link_to new_credit_card_path, class:"main__content__buy__inner__section__div__link" do
                  %i.fas.fa-plus-circle
                    登録してください

          %section.main__content__buy__inner__section
            .main__content__buy__inner__section__div
              %h 配送先
              .main__content__buy__inner__section__div__address
                = user_post_code(@address)
                %br
                = safe_join(user_address_info(@address).split("\n"),tag(:br))
                %br
                = user_full_name(@address)
          .main__content__buy__inner__btn
            = link_to pay_item_path(@item), class: "main__content__buy__inner__btn" do
              購入を確定する

  = render 'partial/new-footer'

app/views/items/create.html.haml
.wrapper
  = render 'partial/new-header'
  .main
    .main__content
      .main__content__create
        .main__content__create__box
          商品の出品が完了しました
          %br
          = link_to root_path,class: "main__content__create__box__link" do
            トップページに戻る
          = link_to item_path(@item.id),class: "main__content__create__box__link" do
            商品詳細ページをみる
  = render 'partial/new-footer'

app/views/items/edit.html.haml
.wrapper
  = render 'partial/new-header'

  .main
    .main__content
      - if @item.errors.any?
        .main__content__error
          - @item.errors.full_messages.each do |message|
            %li= message
      = form_for @item do |f|
        .main__content__img-up
          .main__content__img-up__photo
            %span#label 出品画像
            %span#required 必須
          .main__content__img-up__text
            最大10枚までアップロードできます

          #image-box
            #previews
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  = image_tag image.url.to_s, data: { index: i }, width: "118", height: '118'

            = f.fields_for :images do |i|
              .js-file_group{ data: {index: "#{i.index}"}}
                = i.file_field :url, class: 'main__content__img-up__file__l__field__file'
                %span.js-remove  削除

              - if @item.persisted?
                = i.check_box :_destroy, data: { index: "#{i.index}" }, class: 'hidden-destroy'

            - if @item.persisted?
              .js-file_group{ data: {index: "#{@item.images.count}"}}
                = file_field_tag :url, name: "item[images_attributes][#{@item.images.count}][url]", class: "main__content__img-up__file__l__field__file"
                .js-remove 削除

        .main__content__item-name
          .main__content__item-name__name
            %span#label 商品名
            %span#required 必須
          = f.text_field :name, class: "main__content__item-name__form", placeholder: "40文字まで"
          .main__content__item-name__text
            %span#label 商品の説明
            %span#required 必須
          = f.text_area :text, class:"main__content__item-name__text__form", placeholder: "商品の説明（必須 1,000文字以内）"
          .main__content__item-name__count
            %span.main__content__item-name__count__text 0/1000
        .main__content__item-detail
          .main__content__item-detail__label
            %span#grey-label 商品の詳細
          .main__content__item-detail__category
            %span#label カテゴリー
            %span#required 必須


            #category-select
              = f.collection_select :category_id, @parents, :id, :name, {selected:@item.category.parent.parent.id},{ class: "main__content__item-detail__select select-parent"}

              = f.collection_select :category_id, @category_child_array, :id, :name, {selected:@item.category.parent.id},{ class: "main__content__item-detail__select select-child" }

              = f.collection_select :category_id, @category_grandchild_array, :id, :name, {selected:@item.category.id},{ class: "main__content__item-detail__select select-grandchild" }




          .main__content__item-detail__category
            %span#label サイズ
            %span#required 必須
            = f.select :size, Item.sizes.keys, {prompt: "選択してください"}, {class: "main__content__item-detail__select"}
          .main__content__item-detail__brand
            = f.fields_for :brand do |brand|
              %span#label ブランド
              %span#arbitrary 任意
              = brand.text_field :name, class: "main__content__item-detail__form", placeholder: "例）シャネル"
          .main__content__item-detail__status
            %span#label 商品の状態
            %span#required 必須
            = f.select :condition, Item.conditions.keys, {prompt: "選択してください"}, {class: "main__content__item-detail__select"}
        .main__content__item-delivery
          .main__content__item-delivery__label
            %span#grey-label 配送について
          .main__content__item-delivery__cost
            %span#label 配送料の負担
            %span#required 必須
            = f.select :shipping_cost, Item.shipping_costs.keys, {prompt: "選択してください"}, {class: "main__content__item-delivery__select"}
          -# この部分はあとでJSで表示
          .main__content__item-delivery__cost
            %span#label 配送方法
            %span#required 必須
            = f.select :delivery_method, Item.delivery_methods.keys, {prompt: "選択してください"}, {class: "main__content__item-delivery__select"}
          -# ここまで
          .main__content__item-delivery__area
            %span#label 発送元の地域
            %span#required 必須
            = f.select :delivery_area, Item.delivery_areas.keys, {prompt: "選択してください"}, {class: "main__content__item-delivery__select"}
          .main__content__item-delivery__date
            %span#label 発送までの日数
            %span#required 必須
            = f.select :delivery_date, Item.delivery_dates.keys, {prompt: "選択してください"}, {class: "main__content__item-delivery__select"}
        .main__content__item-price
          .main__content__item-price__label
            %span#grey-label 価格（¥300〜9,999,999）
          .main__content__item-price__box
            .main__content__item-price__box__text
              %span#label 販売価格
              %span#required 必須
            .main__content__item-price__box__form
              %span.main__content__item-price__box__form__doll
                ¥
              = f.number_field :price, class: "main__content__item-price__box__form__form", placeholder: "0"
          .main__content__item-price__fee
            .main__content__item-price__fee__label
              %span.main__content__item-price__fee__label__text
                販売手数料（10%）
            %span.main__content__item-price__fee__price -
          .main__content__item-price__profit
            .main__content__item-price__profit__label
              %span.main__content__item-price__profit__label__text
                販売利益
            %span.main__content__item-price__profit__price -
        .main__content__btn
          = f.submit "変更する", class:"main__content__btn__submit"
          = link_to "#" do
            もどる
        .main__content__text
          %p
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

  = render 'partial/new-footer'

app/views/items/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "banner"
  = render "footer"
  = render "purchase"

app/views/items/pay.html.haml
.wrapper
  = render 'partial/new-header'

.new-wrapper
  .new-wrapper__main
    .new-wrapper__main__create
      商品の購入が完了しました
      %br
      = link_to root_path,class: "link-blue" do
        トップページに戻る

= render 'partial/new-footer'

app/views/items/show.html.haml
= render "header"
.show-main
  .itembox
    .itembox__name
      .h1
        = @item.name
    .itembox__body
      .itembox__body__image
        .itembox__body__image__main
          - @item.images.first(1).each do |image|
            = image_tag image.url.to_s,class: "itembox__body__image__main__photo"
        .itembox__body__image__sub
          .itembox__body__image__sub__thumb
            - @item.images.each do |image|
              = image_tag image.url.to_s,class: "itembox__body__image__sub__thumb__photo"
    .itembox__price
      %a ¥
      = @item.price
      .itembox__price__detail
        (税込)送料込み
    .itembox__detail
      = safe_join(@item.text.split("\n"),tag(:br))
    .table
      %table
        %tbody
          %tr
            %th
              出品者
            %td
              = @user.nickname
          %tr
            %th
              カテゴリー
            %td
              - @category.ancestors.each do |ancestor|
                = ancestor.name
                %br
              = @category.name
          %tr
            %th
              ブランド
            %td
              - if @brand.name != ""
                = @brand.name
              - else
                無し
          %tr
            %th
              商品のサイズ
            %td
              = @item.size
          %tr
            %th
              出品の状態
            %td
              = @item.condition
          %tr
            %th
              配送料の負担
            %td
              = @item.shipping_cost
          %tr
            %th
              発送元の地域
            %td
              = @item.delivery_area
          %tr
            %th
              発送の目安
            %td
              = @item.delivery_date
    .itembox__btns
      .itembox__btns__contents-btn
        - if user_signed_in? && current_user.id == @item.seller_id
          .itembox__btns__contents-btn__seller-menu
            .itembox__btns__contents-btn__seller-menu__edit
              = link_to edit_item_path(@item) do
                編集
            .itembox__btns__contents-btn__seller-menu__destroy
              = link_to item_path(@item), method: "delete", data: { confirm: '商品を削除しますか？削除した商品は元に戻せません。' } do
                削除
        - else
          - if @item.buyer_id.present?
            .itembox__btns__contents-btn__seller-menu__soldout
              %a soldout
          - else
            .itembox__btns__contents-btn__seller-menu__buy
              = link_to buy_item_path(@item), class:"show-wrapper__main__buy-button" do
                商品購入へ進む


= render "footer"