config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :users, only: [:show, :destroy]
  resources :credit_cards, only: [:new, :create, :show, :destroy] 
  resources :items do
    collection do
      get "get_delivery_method"
      get "set_parents"
      get "set_children"
      get "set_grandchildren"
    end
    member do
      get "buy"
      get "pay"
    end
  end
end

app/views/mypage/_show.html.haml
.main-content__side
  .main-content__side__nav
    .main-content__side__nav__list
      .main-content__side__nav__list__item
        = link_to 'マイページ', '#'
      .main-content__side__nav__list__item
        = link_to '出品する', '#'
      .main-content__side__nav__list__item
        = link_to '出品した商品 - 出品中' , '#'
      .main-content__side__nav__list__item
        = link_to '出品した商品 - 取引中' , '#'
      .main-content__side__nav__list__item
        = link_to '出品した商品 - 売却済み' , '#'
      .main-content__side__nav__list__item
        = link_to '購入した商品 - 取引中' , '#'
      .main-content__side__nav__list__item
        = link_to '購入した商品 - 過去の取引' , '#'
      %h3.main-content__side__nav__list__head
        設定
    .main-content__side__nav__list
      .main-content__side__nav__list__item
        = link_to 'プロフィール' , '#'
      .main-content__side__nav__list__item
        = link_to '発送元・お届け先住所変更' , '#'
      .main-content__side__nav__list__item
        = link_to '支払い方法' ,'#'
      .main-content__side__nav__list__item
        = link_to 'メール/パスワード' , '#'
      .main-content__side__nav__list__item
        = link_to '本人情報' , '#'
      .main-content__side__nav__list__item
        = link_to '電話番号の確認' , '#'
      .main-content__side__nav__list__item
        = link_to 'ログアウト' , "#"

app/views/mypage/_side.html.haml
.main-content__side
  .main-content__side__nav
    .main-content__side__nav__list
      .main-content__side__nav__list__item
        = link_to 'マイページ', user_path(current_user.id)
      .main-content__side__nav__list__item
        = link_to '出品する', new_item_path
      %h3.main-content__side__nav__list__head
        設定
    .main-content__side__nav__list
      .main-content__side__nav__list__item
        -if @card.blank?
          = link_to '支払い方法', new_credit_card_path
        -else
          = link_to '支払い方法', credit_card_path(@card)
      .main-content__side__nav__list__item
        = link_to "ログアウト", user_path(current_user.id), method: "delete"

app/views/mypage/mypage.html.haml
.header
  ヘッダー部分
.main-content
  .main-content__side
    .main-content__side__nav
      .main-content__side__nav__list
        .main-content__side__nav__list__item
          = link_to 'マイページ', '#'
        .main-content__side__nav__list__item
          = link_to '出品する', '#'
        .main-content__side__nav__list__item
          = link_to '出品した商品 - 出品中' , '#'
        .main-content__side__nav__list__item
          = link_to '出品した商品 - 取引中' , '#'
        .main-content__side__nav__list__item
          = link_to '出品した商品 - 売却済み' , '#'
        .main-content__side__nav__list__item
          = link_to '購入した商品 - 取引中' , '#'
        .main-content__side__nav__list__item
          = link_to '購入した商品 - 過去の取引' , '#'
        %h3.main-content__side__nav__list__head
          設定
      .main-content__side__nav__list
        .main-content__side__nav__list__item
          = link_to 'プロフィール' , '#'
        .main-content__side__nav__list__item
          = link_to '発送元・お届け先住所変更' , '#'
        .main-content__side__nav__list__item
          = link_to '支払い方法' ,'#'
        .main-content__side__nav__list__item
          = link_to 'メール/パスワード' , '#'
        .main-content__side__nav__list__item
          = link_to '本人情報' , '#'
        .main-content__side__nav__list__item
          = link_to '電話番号の確認' , '#'
        .main-content__side__nav__list__item
          = link_to 'ログアウト' , "logout#index"

  .main-content__right
    .main-content__right__header
      .main-content__right__header__icon
        = link_to image_tag("member_photo_noimage_thumb.png", width: '60', alt: "サンプル画像", class:"app"), "/"
      %h2.main-content__right__header__bold
        megane
      %h2.main-content__right__header__bold
        出品数

    %h2.main-content__right__tab
      購入した商品
    %ul.main-content__right__history
      %li.main-content__right__history__active
        %h3
          = link_to '取引中' , '#'
      %li.main-content__right__history__non-active 
        %h3
          = link_to '過去の取引' , '#'
    .main-content__right__content
      %ul.main-content__right__content__active
        %li.main-content__right__content__active__not-found 取引中の商品がありません
      %ul.main-content__right__content__non-active
        %li.main-content__right__content__non-active__not-found
          -# 過去に取引した商品がありません
.footer